import argparse


def parse_args() -> argparse.Namespace:
    """
    Parse command-line arguments for perf_compare.

    Overview of CLI design:
    -----------------------
    - Positional arguments:
        * configs: one or more "meta-config" JSON files. Each meta-config
          describes logical runs WITHOUT specifying the backend. For each
          logical run, this script will generate two concrete configs:
          backend="scalar" and backend="neon".

    - Optional arguments:
        * -b / --binary:
            Path to the compiled ray tracer binary.
            Default: ./target/release/raytracer

        * -r / --runs-dir:
            Directory where the ray tracer writes its metrics_*.txt files.
            Default: runs

        * --perf-dir:
            Directory where this script will write perf_<run_id>.txt files.
            If not provided, it defaults to the same value as --runs-dir.

        * --perf:
            Name or path of the `perf` executable.
            Default: perf

        * --delete-temp:
            If present, delete temporary files created by the script
            (backend-specific JSON configs, perf_tmp_*.txt, etc.).
            If not present, keep them.

        * --csv:
            If present, generate compare_<label>.csv files in addition to
            human-readable text reports.
    """
    parser = argparse.ArgumentParser(
        description=(
            "Execute paired ray tracer runs (scalar + neon) under `perf stat`, "
            "then compare all collected metrics for each logical run defined "
            "in one or more meta-config JSON files."
        )
    )

    # Positional: one or more meta-config JSON files
    parser.add_argument(
        "configs",
        nargs="+",
        help=(
            "Paths to meta-config JSON files (typically under scripts/config/). "
            "Each meta-config describes logical runs WITHOUT a backend field. "
            "For each logical run, this script will generate scalar + neon "
            "concrete configs and compare their metrics."
        ),
    )

    # 🔹 AQUÍ CAMBIA: default apunta a raytracer/target/release/raytracer
    parser.add_argument(
        "-b",
        "--binary",
        default="raytracer/target/release/raytracer",
        help=(
            "Path to the compiled ray tracer binary. "
            "Default: raytracer/target/release/raytracer"
        ),
    )

    parser.add_argument(
        "-r",
        "--runs-dir",
        default="raytracer/runs",
        help=(
            "Directory where the ray tracer writes its metrics_*.txt files. "
            "Default: raytracer/runs"
        ),
    )

    parser.add_argument(
        "--perf-dir",
        default=None,
        help=(
            "Directory for perf_<run_id>.txt files generated by this script. "
            "If omitted, the same directory as --runs-dir is used."
        ),
    )

    parser.add_argument(
        "--perf",
        default="perf",
        help=(
            "Name or path of the `perf` executable to use. "
            "Default: perf"
        ),
    )

    parser.add_argument(
        "--delete-temp",
        action="store_true",
        help=(
            "If set, delete temporary files (backend-specific JSON configs, "
            "perf_tmp_*.txt, etc.) after all runs complete. "
            "If not set, temporary files are preserved."
        ),
    )

    parser.add_argument(
        "--csv",
        action="store_true",
        help=(
            "If set, generate an additional compare_<label>.csv file for each "
            "logical run, in addition to the human-readable text report."
        ),
    )

    return parser.parse_args()
